name: update_ca_image

on:
  repository_dispatch:
    types: [update-ca-workflow]    

jobs:  
  update-ca-image:
    runs-on: [ ubuntu-latest ]
    permissions:
      actions: write
      contents: write

    steps:
      - name: Intro
        run: echo "Action was triggered! ca=${{ github.event.client_payload.ca_name }} image=${{ github.event.client_payload.ca_image }} branch=${{ github.event.client_payload.branch }}"
      
      - name: Checkout
        uses: actions/checkout@v4 
        with:
          ref: ${{ github.event.client_payload.branch }}
    
      - name: Update Container Image
        uses: jossef/action-set-json-field@v2.1
        with:
          file: ${{ github.event.client_payload.ca_name }}.ca.auto.tfvars.json
          field: ${{ github.event.client_payload.ca_name }}_image
          value: ${{ github.event.client_payload.ca_image }}
      
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated ${{ github.event.client_payload.ca_name }} ca image

      - name: Trigger update infrastructure action
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update_env_infrastructure